[build]
  publish = "."
  command = ""

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
